<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260807224842 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE album ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE media ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_6a2ca10ca76ed395 RENAME TO IDX_ABED8E08A76ED395');
        $this->addSql('ALTER INDEX idx_6a2ca10c1137abcf RENAME TO IDX_ABED8E081137ABCF');
        $this->addSql('ALTER TABLE "user" ADD active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Album ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE Media ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_abed8e08a76ed395 RENAME TO idx_6a2ca10ca76ed395');
        $this->addSql('ALTER INDEX idx_abed8e081137abcf RENAME TO idx_6a2ca10c1137abcf');
        $this->addSql('ALTER TABLE "user" DROP active');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
    }
}
